# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
#' @useDynLib SA23204169
NULL

#' @title K-Means clustering using Rcpp
#' @description Perform k-means clustering on a data matrix using Rcpp.
#' @param data numeric matrix of data, each row representing a sample
#' @param k the number of clusters
#' @param maxIter the maximum number of iterations allowed
#' @return an integer cluster vector, with each integer representing a group.
#' @examples
#' dat <- as.matrix(iris[,1:2])
#' kmeansCpp(dat, k=3)
#' @export
kmeansCpp <- function(data, k, maxIter = 100L) {
    .Call('_SA23204169_kmeansCpp', PACKAGE = 'SA23204169', data, k, maxIter)
}

